/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JogoDeLuta;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Personagem fusca = new Personagem(new PoderFinal());
        Personagem ferrari = new Personagem(new PoderFogo());
        Personagem lamborguini = new Personagem(new PoderBasico());
        System.out.println(fusca.acertar());
        System.out.println(ferrari.acertar());
        System.out.println(lamborguini.acertar());
        
    }
}
